import {
    Entity,
    PrimaryGeneratedColumn,
    Column,
    OneToMany,
    Generated,
    UpdateDateColumn,
    CreateDateColumn,
    Index
} from "typeorm";
import {UserLocationData} from "./UserLocationData";
import {UserAchievements} from "./UserAchievements";
import {Routes} from "./Routes";
import {Reviews} from "./Reviews";

@Entity()
export class User {
    // TODO: makes sense to use an autogenerated bigint id as primary key
    // and have a secondary key with uuid.
    @PrimaryGeneratedColumn("increment", { type: "bigint"})
    id: number

    @Column()
    @Generated("uuid")
    userId: string

    @Column()
    firstName: string

    @Column()
    lastName: string

    @Column()
    age: number

    @Column({ unique: true })
    email: string

    @Index()
    @Column({type: 'bigint'})
    homeCityId: string;

    @Column("point")
    locationCoordinates: string

    // TODO: look up how Waze does there user point system
    // research: https://www.waze.com//wiki/Canada/Your_Rank_and_Points
    @Column()
    points: number

    @CreateDateColumn({ name: 'created_at'})
    createdAt: Date

    @UpdateDateColumn({name: 'updated_at'})
    updatedAt: Date

    @OneToMany(() => UserLocationData, (userLocationData) => userLocationData.user)
    userLocationDataPoints: UserLocationData[]

    @OneToMany(() => UserAchievements, (userAchievements) => userAchievements.user)
    userAchievements: UserAchievements[]

    @OneToMany(() => Routes, (routes) => routes.author)
    routesAuthored: Routes[]

    @OneToMany(() => Routes, (routes) => routes.author)
    eventsAuthored: Routes[]

    @OneToMany(() => Routes, (routes) => routes.author)
    placesAuthored: Routes[]

    @OneToMany(() => Reviews, (reviews) => reviews.author)
    reviewsAuthored: Reviews[]
}